version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions: #EC2로 넘겨준 파일 모두 ec2-user권한을 갖도록 한다.
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:  # CodeDeploy배포 단계에서 실행할 명령어를 지정한다
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료한다.
      timeout: 60
      runas: ec2-user
  ApplicationStart: #deploy.sh를 ec2-user권한으로 실행하게 된다. 60초 이상이 되면 실패가 된다
    - location: start.sh #엔진에스와 연결되어 있지 않은 Port로 새 버전의 스프링부트를 시작합니다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행되었는지 확인한다.
      timeout: 60
      runas: ec2-user
